CREATE TABLE Shop
(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR (255) NOT NULL DEFAULT '',
    address VARCHAR (255) NOT NULL DEFAULT '',
    description VARCHAR (255) NOT NULL DEFAULT '',
    products INT DEFAULT NULL DEFAULT '',
    has_Offer BOOLEAN NOT NULL DEFAULT FALSE,

    latitude DECIMAL (255) NOT NULL DEFAULT '',
    longitude DECIMAL (255) NOT NULL DEFAULT '',

    PRIMARY KEY(id)

);

